name: flutter_smart_dialog
description:
  An elegant Flutter Dialog solution,
  Easily implement Toast, Loading and custom Dialog,
  Make the use of the dialog easier!
version: 4.9.6+1
homepage: https://github.com/fluttercandies/flutter_smart_dialog
# flutter pub publish --server=https://pub.dartlang.org

environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  # https://pub.dev/packages/flutter_lints
  flutter_lints: ^2.0.0

# The following section is specific to Flutter.
flutter:
